version: '3.9'

services:

  linking-front:
    build: 
      context: ./linking-eduction-security-front
      dockerfile: Dockerfile_dev
    ports:
      - "4200:4200"
    volumes:
      - type: bind
        source: ./linking-eduction-security-front/
        target: /src/app